### ISSUE TITLE
How use tabs instead of spaces ? :/

### ISSUE THREAD

**Issue by sidati** [kokororin/vscode-phpfmt#22]
Hi @kokororin, hope you'r ding well,
I tried to add this setting to my VScode `"phpfmt.indent_with_space": false`, but is still using spaces instead of tabs, how can i change this ??

Thanks in advance 🥇

**Comment by pundoo** [comment]
set `"phpfmt.detect_indent": true`

**Comment by kokororin** [comment]
Fixed in 1.0.23

**Comment by sidati** [comment]
Hi @kokororin, if i change `phpfmt.indent_with_space` to be `2` i get this error :

**Comment by kokororin** [comment]
Please see Readme 'How use tabs instead of spaces with PSR2 enabled ?'

**Comment by sidati** [comment]
Sorry didn't notice the "extra" config, thanks it amazingly works now

**Comment by Serhioromano** [comment]
Still not working for me. Change tabs to spaces. Here is my configuration

```jsoon
    "phpfmt.php_bin": "C:/OSPanel/modules/php/PHP-7.2-x64/php.exe",
    "phpfmt.enable_auto_align": true,
    "phpfmt.detect_indent": false,
    "phpfmt.smart_linebreak_after_curly": true,
    "phpfmt.passes": [
        "PSR2KeywordsLowerCase",
        "PSR2LnAfterNamespace",
        "PSR2CurlyOpenNextLine",
        "PSR2ModifierVisibilityStaticOrder",
        "PSR2SingleEmptyLineAndStripClosingTag",
        "ReindentSwitchBlocks",
        "AlignConstVisibilityEquals",
        "AlignDoubleArrow", 
        "AlignDoubleSlashComments", 
        "AlignEquals",
        "AlignGroupDoubleArrow",
        "AlignPHPCode",
        "AlignTypehint",
        "AutoSemicolon",
        "ConvertOpenTagWithEcho",
        "NewLineBeforeReturn",
        "OnlyOrderUseClauses",
        "PrettyPrintDocBlocks",
        "RemoveSemicolonAfterCurly",
        "ReplaceBooleanAndOr",
        "ShortArray",
        "StripExtraCommaInArray",
        "TrimSpaceBeforeSemicolon"
    ],
    "phpfmt.exclude": [
        "SpaceAfterExclamationMark",
        "ReindentComments",
        "StripNewlineWithinClassBody"
    ],
    "phpfmt.psr2": false,
```
